# Generated by Django 4.1.6 on 2023-04-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkIdentifier',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Base_Share.filelink')),
            ],
        ),
    ]
