# Generated by Django 4.1.6 on 2023-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelink',
            name='link',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
